### ISSUE TITLE
[FHIR] Expose HTTP port 9080

### ISSUE THREAD

**Issue by chgl** [Alvearie/alvearie-helm#47]
Currently, only port 9443 is exposed as a service. Since this endpoint uses a self-signed TLS certificate, it's often challenging to interact with the server from within the cluster without running into TLS errors.

It would be helpful to expose port 9080 as well. - either by default or maybe as an option.

I tried just adding 

```yaml
          ports:
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: http
              containerPort: 9080
              protocol: TCP
```

to the deployment, but it looks like the server.xml has to be modified as well:

```xml
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="-1" httpsPort="9443" onError="FAIL"/>
```

Does it make sense to add a new env var to configure the httpPort first?

```xml
    <!-- not sure the default `-1` does even work here. -->
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="${HTTP_PORT:-1}" httpsPort="9443" onError="FAIL"/>
```
