### ISSUE TITLE
Ingress for Traefik

### ISSUE THREAD

**Issue by christianknell** [Alvearie/alvearie-helm#49]
When using this helm chart (v0.3.0) with the following ingress values
```yaml
ingress:
  enabled: true
  hostname: "mydomain.de"
  rules:
    - host: "mydomain.de"
      paths:
        - "/"
  tls:
    - hosts:
        - "mydomain.de"
      secretName: "mydomain.de-tls"
```
we are receiving "500 Internal Server Error" when accessing the ui via mydomain.de/fhir-server. Are their ingress annotations analogical to [nginx](https://github.com/Alvearie/alvearie-helm/blob/main/charts/ibm-fhir-server/values-nginx.yaml) for the traefik ingress controller?
