### ISSUE TITLE
Relation not found in Postgres DB

### ISSUE THREAD

**Issue by bauerjs1** [Alvearie/alvearie-helm#81]
Hi everybody,

I am not yet sure if this is a issue in the helm chart or in the FHIR server itself. When deploying the server via helm and using an external PostgreSQL as database, the FHIR server is not able to operate and reports "relation xyz not found" SQL errors, where xyz are the table names in the `fhirdata` schema.

As a workaround, I manually execute
```sql
ALTER DATABASE ibm_fhir SET SEARCH_PATH TO fhirdata,"$user",public;
```
so that the server's database user finds all the tables from this schema. Is this something that should be considered by the schema migration job?

However, this looks to me as if the FHIR server does not prepend the schema name to the tables when accessing the DB. Is this the expected behavior?

**Comment by lmsurpre** [comment]
You are right that the fhir server doesn't prepend the schema name to the tables when it constructs SQL.
However, its supposed to set the schema name globally based on the config.

Can you confirm whether your fhir-server-config.json persistence section contains a `currentSchema` field like the following?  https://github.com/LinuxForHealth/FHIR/blob/main/demo/basic/fhir/config/default/fhir-server-config.json#L295

**Comment by bauerjs1** [comment]
Yes I can confirm. The persistence section looks like this:
```json
"datasources": {
    "default": {
        "type": "postgresql",
        "currentSchema": "fhirdata",
        "searchOptimizerOptions": {
            "from_collapse_limit": 12,
            "join_collapse_limit": 12
        }
    }
}
```
I am using chart version 0.7.1 with the following persistence parameters:
```yaml
postgresql:
  enabled: false
db:
  type: postgresql
  host: pg-cluster.databases
  port: 5432
  enableTls: false
  name: ibm_fhir
  user: ibm-fhir
  dbSecret: ibm-fhir-db-credentials
  passwordSecretKey: pgPassword
  schema: fhirdata
schemaMigration:
  enabled: true
  ttlSecondsAfterFinished:
```
